// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.zhss.dfs.namenode.rpc.model;

public interface AllocateDataNodesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zhss.dfs.namenode.rpc.AllocateDataNodesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string datanodes = 1;</code>
   */
  java.lang.String getDatanodes();
  /**
   * <code>optional string datanodes = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatanodesBytes();
}
