// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.zhss.dfs.namenode.rpc.model;

public interface FetchEditsLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zhss.dfs.namenode.rpc.FetchEditsLogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string editsLog = 1;</code>
   */
  java.lang.String getEditsLog();
  /**
   * <code>optional string editsLog = 1;</code>
   */
  com.google.protobuf.ByteString
      getEditsLogBytes();
}
